import { Dream } from '@/types/dream';
import { useDreamsStore } from '@/store/dreamsStore';

// Dates spread across 4 weeks for uptrending insights chart [1, 2, 3, 4].
// Today = 2026-03-24. W4 (0-6d ago), W3 (7-13d), W2 (14-20d), W1 (21-27d).
// Recent dreams skew positive emotions & higher ratings for screenshot appeal.
const SEED_DREAMS: Dream[] = [
  // ── W4: 4 dreams (this week — most active) ──────────────────────────
  {
    id: 'seed-1',
    title: 'Flying Over the Mountains',
    content: 'I was soaring above snow-capped mountains, feeling the cold wind on my face. The clouds parted below me revealing a hidden valley with a turquoise lake. I could control my altitude just by thinking about it. The freedom was intoxicating — I never wanted to land.',
    date: '2026-03-24',
    loggedAt: '2026-03-24T07:12:00.000Z',
    emotion: 'Euphoric',
    themes: ['Flying', 'Travel'],
    isLucid: true,
    dreamType: 'dream',
    rating: 5,
    vividness: 5,
    isFirstPerson: true,
    interpretation: null,
    symbols: [],
    isForgotten: false,
  },
  {
    id: 'seed-2',
    title: 'Underwater Kingdom',
    content: 'I could breathe underwater and discovered an entire civilization beneath the ocean. Crystal towers rose from the seabed, glowing with bioluminescent light. The people there communicated through colors that rippled across their skin. They welcomed me like they had been expecting me.',
    date: '2026-03-23',
    loggedAt: '2026-03-23T08:00:00.000Z',
    emotion: 'Peaceful',
    themes: ['Water', 'Travel'],
    isLucid: true,
    dreamType: 'dream',
    rating: 5,
    vividness: 5,
    isFirstPerson: true,
    interpretation: null,
    symbols: [],
    isForgotten: false,
  },
  {
    id: 'seed-3',
    title: 'Dancing in Zero Gravity',
    content: 'I was in a giant glass space station orbiting Earth. Music was playing from nowhere and I started dancing, floating through corridors in zero gravity. Other people joined, all strangers but it felt like we\'d known each other forever. Pure joy.',
    date: '2026-03-22',
    loggedAt: '2026-03-22T08:40:00.000Z',
    emotion: 'Joyful',
    themes: ['Flying'],
    isLucid: true,
    dreamType: 'dream',
    rating: 5,
    vividness: 4,
    isFirstPerson: true,
    interpretation: null,
    symbols: [],
    isForgotten: false,
  },
  {
    id: 'seed-4',
    title: 'Grandma\'s Kitchen',
    content: 'I was sitting at my grandmother\'s kitchen table. She was cooking something that smelled exactly like her Sunday roast. We talked for hours about things I can\'t quite remember now. When I woke up I could still smell the rosemary.',
    date: '2026-03-21',
    loggedAt: '2026-03-21T06:20:00.000Z',
    emotion: 'Nostalgic',
    themes: ['Family'],
    isLucid: false,
    dreamType: 'dream',
    rating: 4,
    vividness: 3,
    isFirstPerson: true,
    interpretation: null,
    symbols: [],
    isForgotten: false,
  },
  // ── W3: 3 dreams (7-13 days ago) ────────────────────────────────────
  {
    id: 'seed-5',
    title: 'The Endless Library',
    content: 'Wandered through a library that stretched infinitely in every direction. Each book I opened contained memories from my childhood that I had forgotten. The shelves rearranged themselves when I wasn\'t looking. A librarian with no face pointed me to a section labeled "Tomorrow."',
    date: '2026-03-17',
    loggedAt: '2026-03-17T06:45:00.000Z',
    emotion: 'Confusing',
    themes: ['Lost', 'School'],
    isLucid: false,
    dreamType: 'dream',
    rating: 4,
    vividness: 4,
    isFirstPerson: true,
    interpretation: null,
    symbols: [],
    isForgotten: false,
  },
  {
    id: 'seed-6',
    title: 'Talking to a Wolf',
    content: 'A grey wolf appeared on a forest trail and started speaking to me in a calm voice. It told me I was lost but not in the way I thought. We walked together through the woods as autumn leaves fell around us. It felt like the most natural conversation I\'ve ever had.',
    date: '2026-03-15',
    loggedAt: '2026-03-15T07:30:00.000Z',
    emotion: 'Peaceful',
    themes: ['Animals'],
    isLucid: false,
    dreamType: 'dream',
    rating: 4,
    vividness: 3,
    isFirstPerson: true,
    interpretation: null,
    symbols: [],
    isForgotten: false,
  },
  {
    id: 'seed-7',
    title: 'Chased Through the City',
    content: 'Something was following me through dark alleyways of a city I didn\'t recognize. Every door I tried was locked. The streetlights kept flickering off as I passed them. I could hear footsteps getting closer but when I turned around, the street was empty.',
    date: '2026-03-13',
    loggedAt: '2026-03-13T04:30:00.000Z',
    emotion: 'Anxious',
    themes: ['Chased', 'Lost'],
    isLucid: false,
    dreamType: 'nightmare',
    rating: 2,
    vividness: 4,
    isFirstPerson: true,
    interpretation: null,
    symbols: [],
    isForgotten: false,
  },
  {
    id: 'seed-forgotten-1',
    title: '',
    content: '',
    date: '2026-03-12',
    loggedAt: '2026-03-12T06:00:00.000Z',
    emotion: 'Neutral',
    themes: [],
    isLucid: false,
    dreamType: 'dream',
    rating: null,
    vividness: null,
    isFirstPerson: true,
    interpretation: null,
    symbols: [],
    isForgotten: true,
  },
  // ── W2: 2 dreams (14-20 days ago) ───────────────────────────────────
  {
    id: 'seed-8',
    title: 'Late for the Exam',
    content: 'I was running through hallways trying to find my exam room. The room numbers kept changing. When I finally found it, everyone was already leaving. The professor handed me a blank paper and said "You already know the answers." I woke up sweating.',
    date: '2026-03-08',
    loggedAt: '2026-03-08T05:15:00.000Z',
    emotion: 'Anxious',
    themes: ['School', 'Late'],
    isLucid: false,
    dreamType: 'dream',
    rating: 2,
    vividness: 4,
    isFirstPerson: false,
    interpretation: null,
    symbols: [],
    isForgotten: false,
  },
  {
    id: 'seed-9',
    title: 'The Shadow Room',
    content: 'Woke up in a pitch-black room. Shadows moved along the walls forming shapes — hands, faces, animals. I tried to scream but no sound came out. The shadows started closing in, merging into one enormous figure that filled the ceiling.',
    date: '2026-03-05',
    loggedAt: '2026-03-05T03:45:00.000Z',
    emotion: 'Scary',
    themes: ['Death'],
    isLucid: false,
    dreamType: 'nightmare',
    rating: 1,
    vividness: 5,
    isFirstPerson: true,
    interpretation: null,
    symbols: [],
    isForgotten: false,
  },
  // ── W1: 1 dream (21-27 days ago) ────────────────────────────────────
  {
    id: 'seed-10',
    title: 'The Vanishing Road',
    content: 'Driving down a highway at night. The road behind me kept disappearing — just blackness. The headlights only illuminated a few feet ahead. The radio played a song I\'ve never heard but somehow knew all the words to. Eventually the road ended at the ocean.',
    date: '2026-02-28',
    loggedAt: '2026-02-28T06:00:00.000Z',
    emotion: 'Eerie',
    themes: ['Travel', 'Water'],
    isLucid: false,
    dreamType: 'dream',
    rating: 3,
    vividness: 3,
    isFirstPerson: false,
    interpretation: null,
    symbols: [],
    isForgotten: false,
  },
];

export function seedDreams() {
  const state = useDreamsStore.getState();
  // Batch insert all dreams at once to avoid animation/state issues
  useDreamsStore.setState({
    dreams: [...SEED_DREAMS, ...state.dreams],
    stats: {
      ...state.stats,
      totalDreamsLogged: state.stats.totalDreamsLogged + SEED_DREAMS.filter((d) => !d.isForgotten).length,
      totalForgotten: state.stats.totalForgotten + SEED_DREAMS.filter((d) => d.isForgotten).length,
      lastDreamDate: SEED_DREAMS[0].date,
      firstDreamDate: state.stats.firstDreamDate || SEED_DREAMS[SEED_DREAMS.length - 1].date,
    },
  });
  console.log(`✅ Seeded ${SEED_DREAMS.length} dreams`);
}

export function removeSeedDreams() {
  const state = useDreamsStore.getState();
  const seedIds = new Set(SEED_DREAMS.map((d) => d.id));
  // Batch remove all seed dreams at once
  useDreamsStore.setState({
    dreams: state.dreams.filter((d) => !seedIds.has(d.id)),
    stats: {
      ...state.stats,
      totalDreamsLogged: Math.max(0, state.stats.totalDreamsLogged - SEED_DREAMS.filter((d) => !d.isForgotten).length),
      totalForgotten: Math.max(0, state.stats.totalForgotten - SEED_DREAMS.filter((d) => d.isForgotten).length),
    },
  });
  console.log(`🗑️ Removed seed dreams`);
}
